### ISSUE TITLE
拓麻歌子相关问题

### ISSUE THREAD

**Issue by someash** [Yorunina/No-Flesh-Within-Chest#102]
1.为什么拓麻歌子没有中文
2.拓麻歌子给的buff范围问题，我在拓麻歌子饿了的情况下吃下食物，同时获得了饥饿3和一个类似饱和的效果，强大的buff也包括debuff么，而且在大部分效果即将结束的时候突然产生了爆炸把自身周围的展示框都炸掉了

**Comment by Yorunina** [comment]
1. 拓麻歌子是专有名词，不采用音译更准确。
2. 这个buff是武器大师的灵药效果加强版本。
