### ISSUE TITLE
绞肉锯的距离问题

### ISSUE THREAD

**Issue by someash** [Yorunina/No-Flesh-Within-Chest#105]
绞肉锯不吃伸缩机械手，伸缩臂，伸缩工具臂，伸缩攻击臂给的触及或攻击距离增益
在副手持有伸缩机械手时，攻击距离反而更近了。。。

**Comment by Yorunina** [comment]
因为绞肉锯本身的实现并不是攻击，而是一个非常特殊的伤害，在你按下右键的时候不停触发。所以不吃原版的属性加成。
