### ISSUE TITLE
大胃王代码错误导致唯一食物无法获得属性加成

### ISSUE THREAD

**Issue by xXStrayXx** [Yorunina/No-Flesh-Within-Chest#109]
大胃王激活部分代码如下：
    'kubejs:king_of_stomach': function (player, organ, attributeMap) {
        let posMap = getPlayerChestCavityPosMap(player);
        let healthUp = 0
        let attackUp = 0
        let manaUp = 0
        let onlySet = new Set()
        posMap.forEach((value, key) => {
            if (value) {
                let foodPro = Item.of(value.id).getFoodProperties(player)
                if (foodPro) {
                    let nutrition = foodPro.getNutrition()
                    let staturation = foodPro.getSaturationModifier() * nutrition
                    if (!onlySet.has(organ.id)) {
                        healthUp = healthUp + nutrition / 2
                        attackUp = attackUp + staturation / 4
                        onlySet.add(organ.id)
                        if (foodPro.getEffects().length) {
                            manaUp = manaUp + foodPro.getEffects().length * 20
                        }
                    }
                    healthUp = healthUp + nutrition / 8
                    attackUp = attackUp + staturation / 10
                } else {
                    healthUp = healthUp - 2
                    attackUp = attackUp - 0.5
                }
            }
        })
        attributeMapValueAddition(attributeMap, global.HEALTH_UP, Math.floor(healthUp))
        attributeMapValueAddition(attributeMap, global.ATTACK_UP, attackUp)
        attributeMapValueAddition(attributeMap, global.MAX_MANA, Math.floor(manaUp))
    },
从大胃王在任务里的描述“重复菜品带来的提升有限，使用更丰富的菜品提升会更高”来看，这个onlyset应当是用来记录食物id，对每个不在onlyset里面的食物进行额外加成的。
但是……
onlySet.add(organ.id)
organ.id……
造成的直接结果就是，只有最左上角（编号最小）的食物物品可以额外获得属性加成，而这个位置在大胃王流里一般是迷你史莱姆……

**Comment by someash** [comment]
#90
