### ISSUE TITLE
提议添加Clay Soldiers Reborn为赛博斗蛐蛐玩法增加内容

### ISSUE THREAD

**Issue by zhaijineet** [Yorunina/No-Flesh-Within-Chest#110]
Clay Soldiers Reborn为游戏添加了许多不同种类的粘土士兵，非同种士兵会互相攻击
加上胸腔模组对于生物器官的自定义，我认为会增添不少新乐趣

求你了，加进去整合包吧！

**Comment by Yorunina** [comment]
Clay Soldiers Reborn没有高版本的迁移吧，有时间会看看。如果没有高版本迁移的话就爱莫能助了。
