### ISSUE TITLE
基准难度对怪物血量的修改在使用套索放出生物时触发

### ISSUE THREAD

**Issue by xXStrayXx** [Yorunina/No-Flesh-Within-Chest#113]
所以可以搞出一百万血的已驯服的龙
而且把基准难度调回去也不会变血量

**Comment by Yorunina** [comment]
这个也不算问题吧。现在的逻辑是，所有生物在生成的时候会尝试给其打上标签（如果没有设置难度就不打）。所以在没有难度的情况下因为没标签，等到切换到有难度的情况下就会被打上标签并且变换血量。

可以之后搞个默认难度也打上标签。
