### ISSUE TITLE
单人世界tps很低。将近10多秒才计算一个游戏刻，同时帧生成时间也很高，画面卡顿。

### ISSUE THREAD

**Issue by e-legy** [Yorunina/No-Flesh-Within-Chest#114]
![屏幕截图 2024-04-05 130711](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/62096007/8293cfff-81dd-4c79-bae9-3cc65171ab59)
整合包版本0.2.1
[latest.log](https://github.com/Yorunina/No-Flesh-Within-Chest/files/14880133/latest.log)

**Comment by e-legy** [comment]
java参数：-XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Dfml.ignoreInvalidMinecraftCertificates=True -Dfml.ignorePatchDiscrepancies=True -Dlog4j2.formatMsgNoLookups=true
jvm是Zulu-jdk-17.0.10

**Comment by e-legy** [comment]
![屏幕截图 2024-04-05 132502](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/62096007/f443a055-1b39-4643-b982-28c21b74dc31)
更换成Java 21（Zulu-jdk-21.0.2），问题有所缓解，但是还是会有卡顿，两个图表也反映出来了

**Comment by dinghtQAQ** [comment]
我也有这个问题，延迟严重，也尝试更换过jdk

**Comment by e-legy** [comment]
[https://o.tas.sh/#jpo21](url)
[jpo21.json](https://github.com/Yorunina/No-Flesh-Within-Chest/files/14913213/jpo21.json)
这bug已经严重影响游玩了，即便是更换JDK 21在游玩一段时间后依旧会严重卡顿，我用Observable Mod（可视化性能检测）生成了一份检测报告，可以看到所有生物实体都有这个问题

**Comment by Yorunina** [comment]
可以跑个spark报告吗，目前怀疑是Lightmans Currency在低版本存在的检测问题。可以尝试更新Lightmans Currency该mod到最新版本。

**Comment by e-legy** [comment]
> 可以跑个spark报告吗，目前怀疑是Lightmans Currency在低版本存在的检测问题。可以尝试更新Lightmans Currency该mod到最新版本。

[https://spark.lucko.me/lqgWR8uyjz](url)，
[lqgWR8uyjz.zip](https://github.com/Yorunina/No-Flesh-Within-Chest/files/14927928/lqgWR8uyjz.zip)
更新Lightmans Currency前的Spark报告

[https://spark.lucko.me/RxfkOuB2nS](url)，
[RxfkOuB2nS.zip](https://github.com/Yorunina/No-Flesh-Within-Chest/files/14928057/RxfkOuB2nS.zip)
更新Lightmans Currency后的Spark报告

**Comment by e-legy** [comment]
更新Lightmans Currency后问题解决
