### ISSUE TITLE
【d8】使用三角随机生成瘤子词条/双边最大限制

### ISSUE THREAD

**Issue by amejsia** [Yorunina/No-Flesh-Within-Chest#117]
因为只改两三行懒得发pull request了……

现版本瘤子生成的代码中：
https://github.com/Yorunina/No-Flesh-Within-Chest/blob/e47244b564ee51994e9aa36e4db851645ff1564f/kubejs/server_scripts/organ/loot.js#L152-L164

 - 将158行扩散系数改为：
``` javascript
let diffusivity = Math.random() + Math.random() - 1
```
这样子就可以很简明（2d6）得到如下的三角随机分布：
![QQ图片20240411021124](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/61157239/6ec38869-a955-4e24-b308-ef76931857e5)

 - 将160行幸运系数的`floor`函数去掉：
```javascript
let luckElement = Math.sqrt(Math.max(player.getLuck(), 1))
```
如果不去掉的话，按当前的计算会有一个非常大的范围内的幸运取值不会对结果产生任何影响，81幸运和99幸运计算出的幸运系数都会是9，这18点幸运是几个麦乐鸡肾不说，再涨1点就会产生质变什么的，我觉得听起来不太舒适……

 - 将162行的属性计算改为`属性系数 * 新的扩散系数 * 未取整的幸运系数`：
```javascript
let attriValue = Math.min(attri.multi * Math.floor(diffusivity * luckElement * 16 + 1) / 16, attri.max)
attriValue = Math.max(attriValue, -attri.max)
```
另外，通过`Math.floor(x * 16 + 1) / 16`达到类似与原来扩散系数中存在的粒度效果，避免出来一堆乱七八糟的小数。
另另外，设置下限为`-attri.max`，群友说非常有必要。

在上述配置下，100幸运获得力量+9以上瘤子的概率约0.5%，且约有0.002%的概率取到+10力量词条。随幸运变化取到不同属性瘤子的概率变化如图所示，纵轴单位是%。当前版本最高器官幸运值应该是麦乐鸡套的105。
![QQ图片20240411021141](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/61157239/d7dc97f4-951c-4a25-9765-ca1aefd310b6)

我觉得这种概率分布还算可以来着，为了刷瘤子特地去做一整套麦乐鸡，加上幸运饰品和药水和buff操作撑到110左右，找到+10力量的瘤子还蛮有仪式感的来着。特别是这种分布下100以上的幸运每加一点都会大幅提升+10瘤子的概率，这种追求幸运数值极限的感觉我觉得非常带劲。

总之平衡上各种参数都可以改就是了，只是一个个人的思路，拉出来给大伙瞅瞅 \_(:з)∠)_
现在在自己服里跑村规，大伙用了都说好【

**Comment by someash** [comment]
看了都觉得好，我之前就觉得要是幸运效果类似正态分布或者韦伯分布，幸运越高，中位数右移，然后保证了真欧皇（极低概率直接出），和高幸运瘤子收益的平衡，可惜技术力没有

**Comment by amejsia** [comment]
> 看了都觉得好，我之前就觉得要是幸运效果类似正态分布或者韦伯分布，幸运越高，中位数右移，然后保证了真欧皇（极低概率直接出），和高幸运瘤子收益的平衡，可惜技术力没有

我之前也在想，但是幸运高只加属性分布范围不加期望才是一设，就没搞额外的东西

而且加新参数的话也不知道调到多高好【

**Comment by Yorunina** [comment]
可以的，我对游戏数值计算并没有任何的深入研究，因此函数也非常幼稚。我会在master分支中采用该方法作为包括瘤子类的基本随机模式。
