### ISSUE TITLE
关于0.2.1版本当中<机械动力>当中的'存量转信器'对于<功能性存储>里的抽屉容量识别问题

### ISSUE THREAD

**Issue by Simpleeasily** [Yorunina/No-Flesh-Within-Chest#118]
开发者你好，
  我在游玩当中，在使用存量转信器对单个物品的抽屉进行容量识别，然后结果如下，存量转信器的容量只能识别到64个物品，超过64个物品就不再反应(GUI界面那个小宝箱跑到最右边，表示满了的状态)，反则是，在64个物品内的容量识别是正常的，能正常触发红石信号。由于我之前玩过0.1.2的版本的整合包，那个版本里面的抽屉mod是能够正常使用存量转信器的，无论插了多大容量的升级插件，照样是按照百分比来识别容量，现在我想问问目前这个问题或者说状况属于是bug还是(盲猜是bug)其他之类的。希望您百忙之中能抽空看到这个事情，然后看看是啥情况，非常感谢您的制作，我很开心能遇到脆骨症这个整合包，最后，拜托了。
![image](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/36688062/907fe06c-7d9d-45c5-9a19-655af764eb6e)
![image](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/36688062/d1a9a9b5-7871-4d48-a8d5-0774de4b6a68)

**Comment by Yorunina** [comment]
应当是因为使用的functional storage的兼容性问题。
在某次版本中，drawer由create兼容性较好的storage drawer（储物抽屉）替换为了functional storage（功能性存储）。因此可能你之前使用的抽屉是储物抽屉而非功能性存储，因此create对其的兼容性不同。

如果真是如此，那估计要等mod作者自己去尝试进行兼容性更改，或者在对应的mod issue区进行意见的反馈了。这一版本应该不会将功能性存储替换为储物抽屉。

**Comment by Simpleeasily** [comment]
这样，只能看看其他方法了，谢谢回复(辛苦了)
