### ISSUE TITLE
来自群友关于开胸器的改进建议！

### ISSUE THREAD

**Issue by MorryMY** [Yorunina/No-Flesh-Within-Chest#120]
来自GCT灵感新货室的精选（GCT交流群群友共同编辑的在线文档）
————————关于开胸器的改进————————
看的出来，制作组自己也会被开boss胸多一点开不了少一点开死而气的砸桌子，所以在0.2更新了安全开胸器
那他安全了吗？他真安全了吗

新物品：麻醉剂
介绍：
麻醉可以作为喷溅药剂或是可以使用消耗耐久的物品添加进游戏
可以让boss不会受到开胸伤害，并且生物收到麻醉效果时会在血条上显示可开胸的阈值（或者是到了可以开胸的血量闪红）
完全避免了一使大劲给boss留血太少开死/打死
少使劲最后血量只敢空手唯唯诺诺，然后被最后阶段狂怒的boss反杀的操蛋问题
建议做完第一章节 完成基础器官任务就送仨五个
合成：
虚弱药水+缓慢药水＝麻醉剂
（合成界面保留一个瓶子）
                铁粒
麻醉剂                  ⥤麻醉注射剂×9

右键丢出像三叉戟一样扎到生物（换皮带效果只有一点耐久的三叉戟）
左键可以攻击生物造成一点伤害（然后就碎了）
两种方式都可以给予2min麻醉效果（开胸器伤害失效，而且可开胸阈值提升）
麻醉剂+龙息+火药＝麻醉吸入剂×3
丢出去会范围给予麻醉剂效果1min并留下药水云
手术刀：只能打开其他生物的胸腔（安全开胸器的更合理版本）
工作台有序合成：
                           铁板
              铁杆        
  铁杆     
止血钳：在最低能开胸的血量锁死你攻击的生物血量
（可以比较贵，放在后期获得）
感谢制作组的浏览，希望能启发你们对于添加与优化开胸工具的灵感！（支持！

**Comment by Yorunina** [comment]
0.3.0版本添加了安全开胸附魔、创造开胸附魔、远程开胸附魔、无伤开胸附魔。
至于一个廉价的锁血方式还没添加，不过我认为目前来说应当是够用了。
