### ISSUE TITLE
冰火传说 闪电百合和寒霜百合的生成条件bug

### ISSUE THREAD

**Issue by ZexuanSun20** [Yorunina/No-Flesh-Within-Chest#125]
雪地里没有一个寒霜百合，全是闪电百合。而我在热带草原找到了寒霜百合

**Comment by Yorunina** [comment]
好问题，这个应该转到冰火的mod分区下。nfwc没有群系修改的相关mod（除了墓园的），所以大概率是冰火自身的一些小小问题。
