### ISSUE TITLE
可以适配原版剑/斧的附魔“凌迟”无法追加到Tetra的各种剑武器上

### ISSUE THREAD

**Issue by 1IkaMV0OiD5** [Yorunina/No-Flesh-Within-Chest#126]
感觉怪怪的，合成出的模型很大的mod武器在jei里也显示可以贴上，这应该不是feature？

**Comment by Yorunina** [comment]
整合包无法解决该兼容问题，需要去对应mod的issue区提出。目测应该是tetra没有进行兼容，而不是血肉重铸的问题？
