### ISSUE TITLE
血肉重铸肉块消化幸运饼干后崩溃

### ISSUE THREAD

**Issue by mikonomi** [Yorunina/No-Flesh-Within-Chest#129]
肉块消化完幸运饼干后游戏闪退
[crash-2024-04-18_20.15.32-server.txt](https://github.com/Yorunina/No-Flesh-Within-Chest/files/15032846/crash-2024-04-18_20.15.32-server.txt)

**Comment by Yorunina** [comment]
肉块没有判断是否为玩家，已解决
