### ISSUE TITLE
代化

### ISSUE THREAD

**Issue by 15736865855** [Yorunina/No-Flesh-Within-Chest#131]
[更好的树叶渲染优化重铸版](https://www.curseforge.com/minecraft/mc-mods/culllessleaves-reforged)
[实体渲染机制优化](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[配方性能优化](https://www.curseforge.com/minecraft/mc-mods/fastsuite)
[铁氧体磁芯](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[修复GPU内存泄漏](https://www.curseforge.com/minecraft/mc-mods/fix-gpu-memory-leak)
[内存泄漏修复](https://www.curseforge.com/minecraft/mc-mods/fix-gpu-memory-leak)
[流畅加载重置版](https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded)
[平滑区块保存](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[Pluto](https://www.curseforge.com/minecraft/mc-mods/pluto)
[Saturn](https://www.curseforge.com/minecraft/mc-mods/saturn)
[Canary](https://www.curseforge.com/minecraft/mc-mods/canary)

你们优化也太差了吧，别人270多的mod,开光影都有90多帧,你们没开光影才60左右
还有地图能换成[旅行地图](https://www.curseforge.com/minecraft/mc-mods/journeymap)吗,现在的地图真不好用
还有[FTB Essentials](https://www.curseforge.com/minecraft/mc-mods/ftb-essentials-forge)/home 传送到家中 很好用

**Comment by Yorunina** [comment]
优化不差吧，如果你觉得优化差可以跑一个报告出来看一下。
目前FPS低可以考虑加入一个oculus flywheel compat来增加机械动力和光影的兼容性，以及调整你的具体设置（可能开了垂直同步或者锁了60）。
该整合包的优化性能不能说是最好，但是至少能吊打你所说的270多的mod的包。如果有问题的话可能是取决于电脑各自的体质。

上文提到的mod中，绝大部分已经被加入+性能测试筛选过，并不是代表加入优化mod就一定是正面优化，如果没有置信结论是不会随意增加mod的。

除此之外，我认为你混淆了TPS和FPS的概念，上文发出的mod一部分跟FPS没太大关系。

**Comment by Yorunina** [comment]
至于为什么不使用旅行地图，是因为FTB Chunk本身有提供区块加载选择和圈地的功能，同时与任务系统有着兼容性，顺带提供了小地图。在提供地图功能基本一致的情况下，不会添加新的mod来覆盖这个功能。如果用户觉得不合适，可以自己添加而不是要求整合包强制添加作为一个严格要求。

FTB Ess不添加的原因也相同，整合包中提供了类如传送石碑和敲钟人器官的东西来满足玩家home和back的需求。使用指令来满足玩家虽然简单有效，但是毁坏了整体游戏流程的沉浸感，在非服务器要求的情况下，整合包默认加入Ess来降低游戏内沉浸感是不明智的行为。（传送石碑的地位将会受其影响）
