### ISSUE TITLE
内测版关闭后整合包无法启动

### ISSUE THREAD

**Issue by Materialoss** [Yorunina/No-Flesh-Within-Chest#138]
[错误报告-2024-4-29_14.58.08.zip](https://github.com/Yorunina/No-Flesh-Within-Chest/files/15145972/-2024-4-29_14.58.08.zip)
现在的测试版本似乎会因为某些原因无法启动，暂不明了这个bug是如何发生的，可以通过重装整合包本身修复（什么格式化）

**Comment by Yorunina** [comment]
测试版本问题，正式版无该问题
