### ISSUE TITLE
无敌大胃王

### ISSUE THREAD

**Issue by n1994rkiller** [Yorunina/No-Flesh-Within-Chest#14]
因为半夜饿了所以想了这么一个器官，暂时取名为无敌大胃王：
可以根据食物的饱和度和饱食度来像遗物金属板那样增加各种属性，如此一来，只需要在体内放一个无敌大胃王，其余格子全部放汉堡啊薯条果酱面包之类的食物，就可以成为巨无霸数值怪白板战士了！
器官只需要胃，身体内的其余地方都用来放食物，这份力量正是成为大胃王的理由
差不多算是面向沉迷于各种乐事的玩家的器官，让他们专心做饭之余也能大杀四方。为了鼓励营养均衡，或许可以限定放入体内的食品每种只能一个？

**Comment by Yorunina** [comment]
0.1.2 已添加
