### ISSUE TITLE
CurseForge托管 器官描述显示 kubjs.tooltips 而不是属性

### ISSUE THREAD

**Issue by GeneralK** [Yorunina/No-Flesh-Within-Chest#141]
![image](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/7538710/5f6d8190-55e6-4452-a245-11b9ab0844d6)

不知道安装错了 还是其他问题。
游戏版本是 1.19.2， forge 是 43.3.5

**Comment by Yorunina** [comment]
因为没有做英文本地化，所以未知的key就会显示成这样。目前也在招人i18n

**Comment by GeneralK** [comment]
Oh, 好的。需要帮忙吗？
我英文挺好的。 中文一般般 😂

**Comment by Yorunina** [comment]
> Oh, 好的。需要帮忙吗？ 我英文挺好的。 中文一般般 😂

非常需要。如果可以的话能留个联系方式吗？

**Comment by GeneralK** [comment]
有 discord 的话， 加我一下
![image](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/7538710/32dbab7e-80c9-44f0-8b2f-dad5163a5212)
