### ISSUE TITLE
关于整合包的性能问题

### ISSUE THREAD

**Issue by FeichaiMadao** [Yorunina/No-Flesh-Within-Chest#145]
整合包版本为0.2.1hotffix1
硬件配置为3700X+2070super 物理内存32G
具体表现症状为进入游戏后会不断出现卡顿，FPS瞬间降至0，F3显示GPU负载100%，但在资源管理器中实际负载在30%以下，几乎无法游玩
目前不确定是否是由特定模组引发该问题或仅仅是硬件问题导致的个例

**Comment by FeichaiMadao** [comment]
仅限单人游玩时出现问题
在服务器中游玩的时候并没有遇到该问题

**Comment by Yorunina** [comment]
有Spark报告吗，方便跑一份Spark报告出来吗。
