### ISSUE TITLE
［恶性bug反馈］GCT群已经有很多人反馈过了，在2.1ver版本中查询千夜寒配方会…

### ISSUE THREAD

**Issue by MorryMY** [Yorunina/No-Flesh-Within-Chest#153]
千夜寒和它的卷轴独住在小山上的一个加工台里。千夜寒不停地自己绘制着更好的卷轴和玩他的回声密充，他的卷轴正观看着qq群上的群友水群。生活很简单，他们都是快乐的。
直到一天，千夜寒的卷轴听到一个声音从上方传来：
“千夜寒怎么做？”
“我会尽我所能去教他，我的主。”卷轴回答道，它冲进了群友的房间，去除了群友游戏中的所有“鬼妖村正，他呐喊着告诉每一位萌新武器大师只是前期的简单武器，嘶吼着指引他们，用心血传授他们锻造之艺。他令那每一位失去方向的人儿前去接受任务的道路，他令那每一位迷茫徘徊于机械运转的学者学会思索，他令那沉思如何创造奇迹的匠人学会检索。他奉献了自己的一切。”
他的两只眼睛一只变成了末影守卫的眼球，能洞察一切弱点给予地方重创，一只变成了第三只眼，能使得射手迅捷灵敏，百步穿杨
他的卷发变成了地狱中升腾的缠怨藤，他的胃变成了容纳粥批的居所，他的心脏分裂成千千万玫瑰碎心，组合起来有无穷的力量。他的血液滋养了温床，使得邪恶的武器大师被温床近数吞噬，天下重归于李四。
就连他的击败！都变成了吕布手上传世宝枪的手柄，身上的蚊子也变成了绯红蚊子（兄弟，你好香）
    数以千万人收到了他的恩泽，世间传唱着他的赞美诗…但战斗还未结束
同样的声音继续告知她：
“我还是不会做千夜寒。”

抓到你了小馋猫，好吃吗😋
      雨蛙 鼓气 瞪眼 红温 png.

**Comment by Parousia3** [comment]
李四的结合

**Comment by Yorunina** [comment]
真bug假bug？整活在群里就好，别来git上发癫。
