### ISSUE TITLE
疑似火龙导致的错误使存档加载时崩溃

### ISSUE THREAD

**Issue by HDAnzz** [Yorunina/No-Flesh-Within-Chest#155]
打灾厄劫掠的时候游戏崩溃，不是很看得懂日志但是疑似是火龙引起的错误，具体情况不明。一打开存档游戏就会崩溃，现在死档了，使用MCEdit2和Amulet均无法解决。在此附上日志。
[minecraft-exported-crash-info-2024-05-14T16-50-37.zip](https://github.com/Yorunina/No-Flesh-Within-Chest/files/15306213/minecraft-exported-crash-info-2024-05-14T16-50-37.zip)

**Comment by Yorunina** [comment]
ticking entity。对于ticking entity你可以无脑加一个Neruina看看能不能解决。
https://www.curseforge.com/minecraft/mc-mods/neruina
由于包括冰火之类的实体错误太多，因此下版本nfwc会默认置入该mod

**Comment by HDAnzz** [comment]
非常感谢作者大大的回复，添加该mod清除火龙后问题已解决。此外我想问一下这里的Entity's Passengers是否是实体的骑乘者？如果是的话是否是灾厄袭击的征服者由于某种原因骑乘了火龙导致此错误？能否通过某些方法避免此bug的出现？
![image](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/103185216/14ee24ab-e859-47ba-b77d-ab824c2811ca)
不过本人没有尝试过复现此bug，如果作者大大认为此问题能够为整合包的体验提升提供帮助，可以研究一下。期待您的回复！

**Comment by Yorunina** [comment]
> 非常感谢作者大大的回复，添加该mod清除火龙后问题已解决。此外我想问一下这里的Entity's Passengers是否是实体的骑乘者？如果是的话是否是灾厄袭击的征服者由于某种原因骑乘了火龙导致此错误？能否通过某些方法避免此bug的出现？ ![image](https://private-user-images.githubusercontent.com/103185216/330646354-14ee24ab-e859-47ba-b77d-ab824c2811ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODU1NDUsIm5iZiI6MTcxNTc4NTI0NSwicGF0aCI6Ii8xMDMxODUyMTYvMzMwNjQ2MzU0LTE0ZWUyNGFiLWU4NTktNDdiYS1iNzdkLWFiODI0YzI4MTFjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxNTAwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmIwN2EwMmRhZjFhZWVkYWYzOWVmNGM3Y2FiYTE5NmUxZDU4NTU5YzEyZmNmODQ1ODk1OTlmOTlmM2IxYzBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gPI6HG0BQ5BWceiXG8S0GXiOAdid7awCY9qVTzCXwgI) 不过本人没有尝试过复现此bug，如果作者大大认为此问题能够为整合包的体验提升提供帮助，可以研究一下。期待您的回复！

这个问题我也在开服务器的时候遇到过，目前来看需要冰火那边从根本上处理一下，我这边只能在这个实体问题出现之后解决。
