### ISSUE TITLE
[Doc] Server pack link appreciated / [文档] 加入服务器端链接

### ISSUE THREAD

**Issue by N3M0-dev** [Yorunina/No-Flesh-Within-Chest#158]
As a programmer I've been accustomed to find all the information I needed from the README or the wiki in the repo, however I found nothing about the server pack after a walkthrough of the repo. Maybe I missed something, but I strongly advice adding a link to the server pack or attach anything that will lead to the release address of the server pack. After hours of trying to work out the server pack and end up in failure, I came accross the video on Bilibili and then successfully found the server [pack release address](https://pan.quark.cn/s/6b9bdfbdbc18#/list/share). To prevent something like this to happen again, I strongly advice to attach the link to the server pack and some other packs to whether the README file or the wiki page. BTW, the same thing has happened just before in #150. It's just a simple request, hope this issue resolved ASAP.

**Comment by Yorunina** [comment]
Thanks for the feedback. Since git publishing is not the main, I ignored server uploads.
The incompatibility func used in kubejs does make it impossible to simply import everything to the server.
I will upload it soon.
