### ISSUE TITLE
下界合金肌肉能力破坏掉落物

### ISSUE THREAD

**Issue by LunaGlaze** [Yorunina/No-Flesh-Within-Chest#16]
反馈bug，下界合金肌肉能力会破坏掉落物，请在kubejs\server_scripts\organ文件夹的player_hurt.js文件在199行的e.uuid != entity.uuid后面加上这一串：
 && entity.getItem() == null
以修复
万分感谢

**Comment by Yorunina** [comment]
感谢反馈，更改原本的判断方法后该Bug已修，修复版本Beta 0.1.2
