### ISSUE TITLE
器官【夺心魔寄生虫】名称有误，应当改为【夺心魔蝌蚪】

### ISSUE THREAD

**Issue by EnderRankari** [Yorunina/No-Flesh-Within-Chest#161]
根据《博德之门3》、DND规则书及被遗忘的国度wiki，器官【夺心魔寄生虫】的正确名称应当为【夺心魔蝌蚪】（Illithid tadpole）。

**Comment by Yorunina** [comment]
英文名可以改一下，中文就算了。捏他不必完全相同
