### ISSUE TITLE
部分生物胸腔内容缺失

### ISSUE THREAD

**Issue by mrqx0195** [Yorunina/No-Flesh-Within-Chest#163]
新版本加入的先进开胸器和创造开胸附魔可以开胸绝大部分的生物
因此，部分此前难以开胸的生物现在变得易于开胸
以下生物是我已发现的，使用默认胸腔内容（全泥土）的生物（基于0.2.1）：
1.训练人偶
建议：清空，并允许玩家自己放入器官改变其属性
2.命令方块（出现于凋零风暴内部战）
建议：以遗物金属板填充，后续考虑专属遗物器官

**Comment by mrqx0195** [comment]
（补充）3.裂刃王龙（裂刃帝王召唤物）
建议：使用小型生物胸腔模板
4.一些法术的召唤物
建议：与其原型生物一致

**Comment by Yorunina** [comment]
不错，可靠的建议，0.3.0已经添加一部分。
但本质问题是胸腔模组不允许修改默认器官，因此肯定有疏漏。后续会联系胸腔作者看看是否会修复default无法定义的问题，或者是将其forge版本模组开源。

**Comment by mrqx0195** [comment]
> 不错，可靠的建议，0.3.0已经添加一部分。 但本质问题是胸腔模组不允许修改默认器官，因此肯定有疏漏。后续会联系胸腔作者看看是否会修复default无法定义的问题，或者是将其forge版本模组开源。

可以考虑在玩家初次尝试打开其胸腔时进行检测，如果为全泥土则替换为自定义的默认器官
同时在persistentData添加一个boolean来标识是否已打开过，防止玩家用泥土转换为其他器官
