### ISSUE TITLE
升级版本导致的奇怪联机问题

### ISSUE THREAD

**Issue by yeecat97** [Yorunina/No-Flesh-Within-Chest#17]
我0.1.0版本的存档可以正常联机，存档迁移到0.1.1版本之后玩了一会进行局域网联机（我是房主），进来的人一直显示通讯加密中然后他的游戏崩溃（没有报告没有日志），然后再之后迁移回去0.1.0又能正常联机了（联机软件：Openfrp）

**Comment by Yorunina** [comment]
信息不足无法判断，需要日志和更具体的信息。不排除是误操作导致
