### ISSUE TITLE
tps过低的问题

### ISSUE THREAD

**Issue by yansanqianke** [Yorunina/No-Flesh-Within-Chest#170]
在我的电脑上，整合包会出现tps过低的问题，如图：
![043D7791B40E57FC7B5A270A7A361E87](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/78251369/f157a6c3-5feb-40f4-979e-d54c39a5948b)
spark报告如下：
https://spark.lucko.me/rRRurZqJDW
希望能够解决
或者能否提供优化mod的列表，我自己尝试解决

**Comment by Yorunina** [comment]
该spark链接不可用，需要一个新的报告。推测可能跟lightmansCurrency旧版本的卡顿有关，已经收到了多份因为钱包附魔引发的卡顿。但具体还需要报告来进行查看。

**Comment by yansanqianke** [comment]
[rRRurZqJDW.zip](https://github.com/Yorunina/No-Flesh-Within-Chest/files/15484805/rRRurZqJDW.zip)
我可以正常打开链接，这是spark报告导出为文件形式的压缩包

**Comment by yansanqianke** [comment]
[profile-2024-05-25_13.34.59.zip](https://github.com/Yorunina/No-Flesh-Within-Chest/files/15484902/profile-2024-05-25_13.34.59.zip)
这里还有另一些报告

**Comment by Yorunina** [comment]
> [rRRurZqJDW.zip](https://github.com/Yorunina/No-Flesh-Within-Chest/files/15484805/rRRurZqJDW.zip) 我可以正常打开链接，这是spark报告导出为文件形式的压缩包 希望能有所帮助
从报告上分时段来看，tps降低前后并没有明显区别，最大的性能消耗仍旧在各种原版的entity.tick上，最大的mod消耗为alex，但也仅仅是11%。在绝大部分时候，性能都是完全充裕的，甚至有很多的一部分时间，mc本身挂起了server.tick等待下一个tick到来（这是一个非常健康的现象）。

但从上文第一个图片上能够看到，在mspt上能够间接的看到一个spike，一般这可能是由于一些类如old GC等行为引发的，进而导致定期的顿卡，进而引发平均的tps降低。
但实际上看spark报告，在各个周期上GC的频率和耗时都非常正常。所以又基本排除掉了内存的相关问题. . .那似乎排查到这里似乎到达了一个死胡同。

对于这种现象目前没有一个确切的结论。或许你可以尝试减少分配游戏内存到4G，以留出更为充裕的系统内存防止挤占。而后在较为干净的环境下查看是否能够复现该情况。

**Comment by yansanqianke** [comment]
![2024-06-01_10 55 50](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/78251369/e77b846f-4c03-49a0-9ea7-0d7ac6dc18dd)
在3.0中该问题已消失，麻烦你们了

**Comment by Yorunina** [comment]
目测应当是类如莱特曼货币之类的mod的旧版遗留tps问题，新版本更新后解决
