### ISSUE TITLE
【刷物品bug】复刻怪使用血肉漏斗复制物品bug

### ISSUE THREAD

**Issue by KorakuRyou** [Yorunina/No-Flesh-Within-Chest#174]
血肉重铸的血肉漏斗可以取下生物手持物品，这导致玩家可以通过手持任意物品攻击alex生物中的复刻怪再用血肉漏斗取下来无限复制物品。

**Comment by Yorunina** [comment]
已知问题，所以0.3.0复刻怪被禁用了生成（本身也无太大必要作用）
