### ISSUE TITLE
打开某些战利品箱子导致服务器崩溃

### ISSUE THREAD

**Issue by AminoBatlog** [Yorunina/No-Flesh-Within-Chest#176]
崩溃日志如下:
[crash-2024-06-01_17.21.20-server.txt](https://github.com/user-attachments/files/15521165/crash-2024-06-01_17.21.20-server.txt)

在崩服多次之后反复尝试了5,6次, 突然就只是卡掉了玩家, 没有崩服, 然后那个箱子就正常生成了, 不大清楚造成问题的原因

**Comment by Yorunina** [comment]
已知问题（0.1.2版本已知），Lootjs在生成战利品时会尝试使用AnyStructure方法判断当前结构，这会调用到一个getChunk（一个性能很差的方法）。对于某些服务器，这个问题可能会导致tick超时而引发的崩溃。

没有预期解决方法，要么完全舍弃所有与战利品相关的魔改设计，要么等forge或者原版去修复这个问题。
