### ISSUE TITLE
Cursery引发的服务器崩溃

### ISSUE THREAD

**Issue by StarrySky7D4** [Yorunina/No-Flesh-Within-Chest#178]
[crash-2024-06-03_14.07.39-server.txt](https://github.com/user-attachments/files/15529635/crash-2024-06-03_14.07.39-server.txt)
3.0Beta版本的整合包服务器端异常崩溃日志

**Comment by Yorunina** [comment]
旧版本存档？新版本已经禁用了爆炸诅咒的负面附魔，因为在0.2.1开发直播的时候就已经遇到这个情况了。

**Comment by StarrySky7D4** [comment]
3.0beta版的存档
