### ISSUE TITLE
糖果胃的一个奇怪互动

### ISSUE THREAD

**Issue by unodra** [Yorunina/No-Flesh-Within-Chest#18]
装备糖果胃之后尝试所有nbt标签被列为糖果的食物之后，出现以下情况：
整合包魔改的糖果：给糖果之梦，进入冷却，糖果之梦持续15秒
额外乐事的焦糖糖果：给糖果之梦，进入冷却，糖果之梦持续30秒
额外乐事的其他糖果：给一瞬间的糖果之梦，进入冷却

**Comment by unodra** [comment]
另外，尝试做糖果心的时候会出现，由于和玫瑰心第一步重复而导致默认切割成玫瑰心的情况

**Comment by Yorunina** [comment]
糖果胃是根据糖果的提供饥饿值进行结算的，每有1饥饿就给予15s。第二点确实是bug，0.1.2版本修复
