### ISSUE TITLE
使用饰品“狂暴之心”时，服务器日志不断出现“Skipping Entity with id”

### ISSUE THREAD

**Issue by OrzMiku** [Yorunina/No-Flesh-Within-Chest#184]
当有玩家使用饰品“狂暴之心”时，服务器日志不断出现“Skipping Entity with id”。

https://github.com/Yorunina/No-Flesh-Within-Chest/assets/42781101/a74bebaa-8a56-4a3c-b83c-61268027cfea

服务器版本：0.3.2
服务器日志：https://mclo.gs/uFg7bKa

**Comment by Yorunina** [comment]
已知问题，因mod闭源无法修复，需暂时屏蔽该log，无性能影响。
后续版本会禁用该饰品，或者直接更换饰品mod。
