### ISSUE TITLE
不支持Java22

### ISSUE THREAD

**Issue by wellcoming** [Yorunina/No-Flesh-Within-Chest#187]
无法使用`JRE22`启动此整合包，已测试改用`JRE21`可以正常运行  
[错误日志](https://gist.github.com/wellcoming/a73e6e430c94b1b454e154603ea4142b)

### 环境
- Arch Linux
- jre-openjdk

**Comment by Yorunina** [comment]
部分mod不支持j22，这不是整合包作者能解决的问题，应当排查对应的mod列表之后，挨个要求各个mod作者进行整改。
但是这么做本身收益不高，且战线过长，并不划算，因此本issue不受理。

**Comment by wellcoming** [comment]
建议在`README.md`中说明，防止出现不必要的问题。
