### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by 15736865855** [Yorunina/No-Flesh-Within-Chest#195]
【真正的必备模组！这些功能不再是幻想！53个实用/美化/辅助模组 我的世界模组介绍】https://www.bilibili.com/video/BV15Z421p7D8?vd_source=55f65a8d1cabef57ca0618ea255454af
里面有mod很不错,看看是否可以加入

**Comment by Yorunina** [comment]
非必要不新增，而且你的git issue标题太短了，之后这种不符合规范的issue不再受理。
