### ISSUE TITLE
革命·蒸汽机与焰魔肝脏的冲突

### ISSUE THREAD

**Issue by Crazypeak** [Yorunina/No-Flesh-Within-Chest#200]
Version：0.3.2
（熔火心+蒸汽机+怀表）+（不灭核心+焰魔肝脏），焰魔力量V正常自动叠加，但吃煤炭在熔火状态结束后，该有的心火buff未有成功转换出来

**Comment by Yorunina** [comment]
让群友测试了一下，2位群友都说是正常的，我这里也是正常的。无法复现，证据不足
