### ISSUE TITLE
关于增加整体游戏性的一些建议

### ISSUE THREAD

**Issue by SXSWJSZY** [Yorunina/No-Flesh-Within-Chest#21]
1.整合包的核心是器官，所以我建议加强这个要素，适当放低其他要素，说白了就是加强器官的数值，整合包里装备强度较低，但是怪的强度挺高，也挺适合器官玩法发挥的；
2.关于器官的一些新能力：比如，某个特殊器官数值较低，但是可以为玩家增加一个饰品栏位（我下面会推荐一个国产高质量饰品模组，正好搭配），或者“增生脊柱”“强化心脏”之类，加了这个器官就会多几个器官槽位，可以加装外骨骼之类的挂载器官，外骨骼和体内器官做区分，拥有耐久度，但是可以进行特殊附魔之类的；
3.关于前期玩法，这一点整合包真的做的很好，因为所有玩家都会想着往外探索，获取更多有趣器官，但是是不是可以做的更有积极性一点？我的建议是，加入品质系统（当然要和游戏里已经存在的稀有度系统做区分），比如破烂、普通、优秀三个品质（我觉得三个正好），之间有细微的数值差异，这也正好契合我上面说的“加强器官数值”，毕竟区间拉大了，这种细分才更好做，但是要注意一点，品质绝对不能跨t度，优秀品质的器官绝对不能强于t1器官
4.上面说到游戏吸引力，我认为把所有特殊器官一次性全部展示出来是比较失败的做法，这在一定程度上会打击玩家的好奇心和探索欲望，加强功利性，我的建议是只露出一部分信息，不透露具体数据和能力，只露出你们写的那些备注什么的，这个要你们自己把握度了
5.关于模组推荐：就是前面提到的饰品模组，月之石（moonstone），拥有上百个饰品，并且完美覆盖整合包里那个模组，每个制作都很精良，并且有升级合成体系，适配我说的“加额外饰品栏位的器官”；
6.精妙背包的经验泵会和emi冲突，无法用滚轮调整经验等级，因为他默认把滚轮功能用在了emi的页面上（所以为什么不用jei？）
7.最后强调一下，我只是作为玩家提出的建议，不是什么专业人员，只是希望你们可以采纳一些而已
最后希望多多更新，这种精良的整合包现在太少见了，希望能成为国内标杆，同时火到外网

**Comment by SXSWJSZY** [comment]
> 1.整合包的核心是器官，所以我建议加强这个要素，适当放低其他要素，说白了就是加强器官的数值，整合包里装备强度较低，但是怪的强度挺高，也挺适合器官玩法发挥的； 2.关于器官的一些新能力：比如，某个特殊器官数值较低，但是可以为玩家增加一个饰品栏位（我下面会推荐一个国产高质量饰品模组，正好搭配），或者“增生脊柱”“强化心脏”之类，加了这个器官就会多几个器官槽位，可以加装外骨骼之类的挂载器官，外骨骼和体内器官做区分，拥有耐久度，但是可以进行特殊附魔之类的； 3.关于前期玩法，这一点整合包真的做的很好，因为所有玩家都会想着往外探索，获取更多有趣器官，但是是不是可以做的更有积极性一点？我的建议是，加入品质系统（当然要和游戏里已经存在的稀有度系统做区分），比如破烂、普通、优秀三个品质（我觉得三个正好），之间有细微的数值差异，这也正好契合我上面说的“加强器官数值”，毕竟区间拉大了，这种细分才更好做，但是要注意一点，品质绝对不能跨t度，优秀品质的器官绝对不能强于t1器官 4.上面说到游戏吸引力，我认为把所有特殊器官一次性全部展示出来是比较失败的做法，这在一定程度上会打击玩家的好奇心和探索欲望，加强功利性，我的建议是只露出一部分信息，不透露具体数据和能力，只露出你们写的那些备注什么的，这个要你们自己把握度了 5.就是前面提到的饰品模组，月之石（moonstone），拥有上百个饰品，并且完美覆盖整合包里那个模组，每个制作都很精良，并且有升级合成体系，适配我说的“加额外饰品栏位的器官”；
6.最后强调一下，我只是作为玩家提出的建议，不是什么专业人员，只是希望你们可以采纳一些而已 最后希望多多更新，这种精良的整合包现在太少见了，希望能成为国内标杆，同时火到外网

**Comment by Yorunina** [comment]
1. 目前由于是早期版本，对于器官Build的开发也只是我一个人在做，后续会逐步强化这方面的内容。
2. 增加饰品栏位是不会采纳的，除此之外，在某些条件下增加器官槽位需要修改胸腔原Mod的修改支持，目前无法做到。制作所谓体外器官与体内相差异也是同理暂时技术上无法实现。（如果能实现我大概早就实现了吧，因为我个人是喜欢把一些有趣的技术点提前都给暴露出来）
3. 随机属性是一开始在考虑的一件事情，但最后还是采用了固定属性作为游戏的核心，最主要原因是为了降低肝度和后期build的可重复性。如果采用随机属性，玩家在后期将会陷入**刷子游戏**的陷阱之中。虽然这对延长游戏时长有作用，但是正如我在第四章最后任务所说，我不希望这个整合浪费太多玩家的时间，它的内容就这些，最多让玩家尝试几种build就已经很不错了。强制通过这种随机属性来延长游戏时长并无太多意义。（虽然随机属性也会对玩家的探索产生鼓励作用，但这促进几乎微乎其微，尤其是在MC的后期探索新的地区代价异常大，因此这不能称之为一个特别优秀的主意）。不过如果后续做类暗黑的RPG包会考虑此类建议。
4. 你说的很好。但是现在有玩家甚至让我们展示出所有boss列表。玩家之间亦有区分，有些玩家依靠自己的探索就可以了解游戏的全貌，而有的如果不加以指引就会放弃游戏并称你为粪包。在我考虑了多方权衡之后把这个包定位成了入门级别的水槽冒险包，因此这个列表是**必不可少**甚至现在是有些不够详细的。我一开始甚至想要用无任务RLC式的玩法来引入所有内容。但是RLC的成功是不可复现的，它是由媒体综合造就的“精品”冒险整合包。所以切勿落入玩家个人视角陷阱，要以较低水准玩家的视角来审视游戏引导与游戏内容。
5. 月之石，恕我直言是垃圾mod，不仅会导致整合包稳定性大幅下降，其数据和属性完全不可控，只有在低质量整合包中才能出现。而且大量饰品会导致器官的地位下降，不可取。神秘遗物也是同理，不过稳定性好一些。（而且月之石里面的饰品我们可以通过器官完全复刻一遍，如果不加月之石，说不定还能成为我们的灵感池——虽然它的灵感并不优秀就是了）
6. 该问题我之后会check。之所以使用EMI是因为我希望玩家能够使用一些新时代的mod。但是你怎么知道我没用JEI？其实这个包里已经安装了JEI，使用的是一个特性，即EMI在同时安装JEI的情况下会使用自己的界面，但搜索使用的是JEI的引擎。如果你觉得这个问题影响很大，可以在我们修复之前先删掉EMI，使用剩下的JEI理论上也是可以正常运行的。（当然你也要删掉EMI Loot）
