### ISSUE TITLE
【BUG】多人游戏中玩家可窃取其他玩家背包

### ISSUE THREAD

**Issue by feiqiuquq** [Yorunina/No-Flesh-Within-Chest#230]
如题，在多人游戏中玩家对着其他玩家的后背右键可以打开其他玩家的背包

**Comment by D7x7z49** [comment]
这不是 bug，那个背包模组就是这样，它是独立实体计算的，类似箱子，驴子+箱子知道吗？而且反馈或者有意见应该反馈给背包那个模组 Sophisticated Backpacks <https://github.com/P3pp3rF1y/SophisticatedBackpacks>

**Comment by hiiiiiiixiaohui** [comment]
不是bug，背包模组自带的功能，自己可以在选定的背包右上角选项内，选择自己的背包是否可被外部打开
