### ISSUE TITLE
请求告知允许主世界生成凋零风暴

### ISSUE THREAD

**Issue by PenForEastCat** [Yorunina/No-Flesh-Within-Chest#243]
整合包是挺好玩的，就是感觉缺点压迫感，找来找去找不到怎么解决无法在主世界召唤凋零风暴的问题，希望告知。

**Comment by PenForEastCat** [comment]
我开的是服务器，即便是单机的解决方法告诉给我也可以，很需要

**Comment by mrqx0195** [comment]
这是整合包的设定，需要推主线任务后在回忆世界召唤凋灵风暴
如果你真的有这方面的需求，请在kubejs/server_script/common/entity_spawn.js中修改（删去第一个event）

**Comment by PenForEastCat** [comment]
> 这是整合包的设定，需要推主线任务后在回忆世界召唤凋灵风暴 如果你真的有这方面的需求，请在kubejs/server_script/common/entity_spawned.js中修改（删去1到19行）

真的非常感谢你提供的帮助，我十分感激
