### ISSUE TITLE
【针对现有流程和器官的改进建议】

### ISSUE THREAD

**Issue by Materialoss** [Yorunina/No-Flesh-Within-Chest#29]
1.针对目前的任务流程，个人认为可以强化的点
1.1 目前的任务流程中存在一些带有重复性的，或是相互之间没有显著差异，显著引导性的任务，比如说
铁魔法任务中【初学者日志】和【铁箍卷册】两个任务的达成条件，分别是合成同名物品，但在铁魔法流程中，两者的既没有较大的造价差异（前者是2铜1线6纸，后者是3链4革2纸），也没有合成上的继承关系（合成后者不需要前者），那么在任务流程中完全可以把两者合并为一个“或门任务”（即达成任意一个条件即可），类似的问题在【章节1：tetra与工具】和【锤】任务中同样存在（两者都要求合成锤）
1.2 目前的任务流程中使用的绿钩任务会导致对任务指引性上的缺失，例如在完成了第一章的【简易、存储、整合】后，对于不熟悉mod的玩家，除了模组名称以外，几乎没有什么指引把玩家带到【如何使用某MOD】：【TOM的简易储存】里。这种情况在本整合内的几乎所有模组教程中都有出现
个人建议可以把这种情况中的后一个任务，从主动激活任务也改为被动激活。例如，在例子中，可以把【简易的简易储存】的任务目标也改为拥有一个存储整合器，从而把玩家引导进这一条支线任务，明确地告诉玩家“这条支线是这个模组的教程”
1.3 其他：
在机械动力教程支线里，【更多的自动化】任务会给玩家一把扳手作为奖励，请问这是为什么？按理来说扳手并不昂贵，而且前期也有一个任务以扳手为目标，这里的重复奖励是为了什么呢？
是否会在后期选择更换目前的ui系统？例如RPGui这样的数值式ui，一来可以更好的和蓝条UI配合，二来本人在游戏中遇到ui会有一些显示的bug，例如当总肺活量大于1时，气泡值实际上此时有两行，但是现在的UI只能显示一行，另一行只有在第一行被消耗掉后才能显示出来

2.针对目前的器官，个人的改进意见
目前的器官设计较为保守，这种保守不是指数值上的（已经有了大量数值怪的器官，例如大胃王或无形肿瘤），而是指机制上，增加了新的机制的器官仍然较少，个人觉得对于数值上的设计实际上可以相对削弱一些，而是添加更多不同的机制
此外，尽管整合包“希望”将器官作为核心，但实际上在游戏流程中，玩家们并不一定需要器官的帮助，器官从“核心”变成了“支线”，个人不成熟的建议是，尽管我在其他帖子里看到有回复说“本包不是一个类暗黑包”，但现在的实际情况是，如果不大改流程的话，玩家中最火的两个流派就是（无形肿瘤流和大胃王流）有着非常浓厚的类暗黑玩法——无形肿瘤无需多言，大胃王虽然数值固定，但是因为农夫乐事系列的存在，也构成了类似暗黑的刷子（只不过刷装备变成了刷食物）
综上，个人对于“器官”这个整体玩法提出的建议是可以适当的在不影响整个发展的情况下，增加一些随机性

3.修改方法
具体的修改肯定是作者们努力，但是本人有一些不成熟的，浅薄的建议，这这里顺便发表出来，希望作者予以斧正，也希望能激发一些作者的灵感
（1）针对目前的器官可以进行一个大的分类，目前已有的器官可以分为【样板】（所有通用器官和模板器官，模板器官等），【魔法】（魔法脊椎，魔法束等）、【机械】（机械动力相关）、【传说】（生物掉落或生物开箱）以及【血肉】（血肉重铸相关，和无形肉块相关）。其中【样板】和【机械】两类没有任何的随机性，做出来是什么就是什么。而【魔法】和【血肉】可以增加一些随机性，在不改变【激活效果】和【特殊效果】前提下，对于【器官属性】可以进行一定的随机性（类似无形肿瘤，但是数值更加保守）
（2）对于不同大类的器官有更明确的分类，【样板】注重“通用性”，【魔法】注重……注重魔法，【机械】强调稳定（目前这个系列最好），【血肉】强调不可控和随机性
（3）【无形肿瘤】可以加入耐久度，耐久度耗尽后会失效（但不会损坏，类似原版鞘翅的机制），可以用【鲜活肉块】修复；【大胃王】会在玩家进食时，有较低的概率吃掉胸腔内储存的食物，并给予玩家一段时间的饱和状态
（4）【巨型器官】从现在的物品形式改为方块形式（可以放到地上，方块模型可以套用血肉重铸的部分模型，例：【巨型肠子】套用【恶性脉络】，【巨型胃】套用【消化器】等等），从而更强调其“巨型”的特点，以及和其他器官区分
（5）个人器官想法：【脏极增生】，灵感来自《以撒的结合》同名模组，合成方法为【大胃王】为原料，序列组装【心脏】【肠子】【肾脏】【脾脏】五次，属性为4点消化效率，4点营养消化效率，有特殊效果：当“当胸腔内储存了食物，并且因受到攻击导致血量降低到半血以下时，脏极会破体而出帮助战斗”，当此效果触发时，会消耗掉一份胸腔内的食物
【脏极增生】，可以套用“饥饿的肉块”的模型，与其本体（玩家/搏鱼）之间有一条无限长度，不会损坏的线（套用缰绳？）连接，脏极会继承本体的所有能力（穿戴相同的装备，有相同的脏器（但是不能被开胸））只有攻击力除外，脏极的攻击力等同于胸腔内，饱食度最高的食物的饱食度。“脏极”每杀死一个敌人，就会给玩家5s的饱和状态（或是再生状态？），持续时间内击杀会延长这个效果，当玩家血量回复到上限60s后，脏极会消失（回归体内），若脏极死亡，玩家也会死亡

**Comment by Saturday13th** [comment]
有考虑过增加更多和附魔相关的内容吗，感觉在这包里附魔存在感好低；
感觉现在的弓箭流和魔法流的强度有点低（可能是因为瘤子和大胃王太过离谱），远程可以加入一些触发类的技能或者增益效果，魔法可以考虑加入新生魔艺（？），至于瘤子可以和扭曲关联进行削弱，大胃王削弱可以重复食物只计算一次

**Comment by Yorunina** [comment]
改动内容过多，请拆分。小规模修改请自行提出Pr。
