### ISSUE TITLE
希望能增加一个能抽取其他生物血清的道具

### ISSUE THREAD

**Issue by AURINNE42** [Yorunina/No-Flesh-Within-Chest#33]
改造其他生物，比如说傀儡，真的是非常不方便。而且因为玩家只能在其他生物生命较低的情况下开胸，往往救都救不回来。建议增加一个能查看其他生物器官数据的道具，或者干脆让血清抽取仪能对其他生物使用.....
另外如果可以希望能在毕业后增加一个用开胸器和指令附魔书合成的，能满血开胸的东西......

**Comment by Yorunina** [comment]
抽取生物血清是可以的。
但是满血开胸的机制可能需要胸腔mod本身来支持。

**Comment by Yorunina** [comment]
0.2.1支持抽取其他血清，满血开胸通过easy_assess属性实现
