### ISSUE TITLE
开胸器物品（应该叫贴图）的bug

### ISSUE THREAD

**Issue by HideUsSaveUs** [Yorunina/No-Flesh-Within-Chest#37]
虽然无伤大雅，但是看着难受，合成出的开胸器和EMI收藏的开胸器图标并不一样，
![image](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/39188665/b84c34b6-1b13-4626-8cfe-b44b64ffa03d)
（图为收藏的开胸器图标）
![image](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/39188665/0021b3ed-aeb6-417e-acfe-0fd5c2224fb9)
（图为合成出的实际开胸器物品）

**Comment by cxey-low** [comment]
当你选择了一个配方再收藏，emi会给它右上角加上一个图标，因此这不是bug
