### ISSUE TITLE
村民交易和交货协议获取的是绿宝石而不是钱币

### ISSUE THREAD

**Issue by leiji001** [Yorunina/No-Flesh-Within-Chest#39]
版本是 0.1.2 服务端

如图
![image](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/94916764/9fbaf996-da59-4099-a31b-1eea859b61ea)
![image](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/94916764/380c5a19-2fcc-4174-833c-bfcb928aae3f)

除任务外没有找到其他获取钱币的方式

**Comment by Yorunina** [comment]
目前设计如此，这个反向交易配方实际上并不是添加的，而是wares模组自己生成的。
原本设计中就只有任务、Boss和地牢箱子能够获取钱币。
