### ISSUE TITLE
关于铁魔法书里的鲜血法杖的问题

### ISSUE THREAD

**Issue by Alvitve** [Yorunina/No-Flesh-Within-Chest#41]
主要是关于鲜血法杖无法塞入对应槽位的问题。因为在游玩的过程中发现，可以从抄写台中将已经装备的魔法书和背包中的鲜血法杖调换从而达到强行装备鲜血法杖的效果。虽然装备后对使用法杖中的魔法无影响，但是强行装备之后，武器大师模组的武器直接失效了，除了连斩一类的主动技能以外，左键无法造成伤害。
还有就是对魔法系的一些抱怨，在tetra的近战和远程，武器大师的近战面前，铁魔法书打出的伤害差距还是有点大的，特别是法师系的套装本身防御力和功能性还不如腾炎套的情况下，在不装备失乐园的情况下，面对神恩boss时三者的差距过于大了。此外，毕业器官无尽之力的伤害加成也无法作用于魔法伤害，希望有更加强力的魔法类器官出现，最好不要只是肿瘤流一家独大

**Comment by Yorunina** [comment]
无法修复该问题，需要等待Iron n spellBook的饰品魔法书分支进行修复。使用这种类似于bug一样的装备方式必然会导致此类问题。
此外，仅从伤害考虑一个体系是不全面的，魔法方面已经有大量的辅助类魔法提供极大的战斗帮助。只能说是没有提供强力输出手段的器官。后续会增加。
