### ISSUE TITLE
关于将人造末地传送门框架替换为钥匙刻字台的建议

### ISSUE THREAD

**Issue by TianPingRain** [Yorunina/No-Flesh-Within-Chest#46]
维度地牢有自带的钥匙刻字台，可用于钥匙刻字，用于代替原版末地传送门框架
钥匙刻字台每被使用一次都会失去一层光泽，使用三次则会损坏消失，如铁砧一样。可在配置中修改可使用次数和损坏几率。
钥匙刻字台可以被正常破坏，避免玩家误放末地传送门框架带来麻烦，或利用框架不可破坏特性做出意料之外的行为。

**Comment by Yorunina** [comment]
非常好的建议，下版本0.1.3修改。
