### ISSUE TITLE
关于自定义初始装备

### ISSUE THREAD

**Issue by CongYuSanXun** [Yorunina/No-Flesh-Within-Chest#50]
希望告知在哪里修改初始装备，希望将FTB任务书加入其他，方便从未了解过整合包的玩家第一时间找到整合包任务。
![001](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/68322529/81d3cc9d-eff1-4dce-9d22-9c9f599c7940)

以及建议添加[Paxi](https://www.mcmod.cn/class/4615.html)和[norundownhouse数据包](https://www.curseforge.com/minecraft/customization/no-rundown-house)
，可以避免在世界原点处生成凋零风暴模组的小屋。

[魔法巫师](https://www.mcmod.cn/class/5238.html)可更新至0.3.3.1最新版，避免出现穿巫师套装遇女巫发生游戏或者服务器崩溃。

**Comment by Yorunina** [comment]
魔法巫师不会更新到最新版，因为最新版魔法巫师存在其他问题。目前分支版本中已使用了我个人编译的修复问题的魔法巫师版本。女巫崩溃的问题已经被修复。
新版本引入了怪奇宝典，后续会把所有的书全部归入怪奇宝典中，在开局给予玩家。

至于凋零风暴小屋的问题。首先kubejs可以全局加载数据包和资源包，所有paxi能做到的kubejs都可以做到。而且暂不打算禁用凋零风暴小屋的生成。
