### ISSUE TITLE
【BUG反馈和修改建议】

### ISSUE THREAD

**Issue by Materialoss** [Yorunina/No-Flesh-Within-Chest#52]
1.整合包中“大骨汤”有两种配方，其中两根骨头的配方需要在厨锅内用“玻璃瓶”盛出，但是在其模型是装在碗里，食用后返还的是一个碗，且另一个配方也是用的碗盛出，是否是这个配方出错了？
2.能否将“稀有矿簇”的“下界合金碎片”产出改为“远古残骸”？在制作一些机械时会用的到
3.能否取消开局时给予的模组教程书？改为在任务流程中获取

**Comment by KALLLAW** [comment]
我们的服务器开战利品箱子会导致崩服，不知道是优化问题还是什么
