### ISSUE TITLE
机械动力任务文本疑问

### ISSUE THREAD

**Issue by yueziji** [Yorunina/No-Flesh-Within-Chest#54]
![屏幕截图 2024-02-22 205621](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/21022131/c9a43a55-546a-460e-922e-5fb68a0f09a1)
找了半天没找到卖机械动力结构的商店，是暂未加入吗

**Comment by Yorunina** [comment]
确实是暂未加入，而且胶囊因为其存在的各种问题，在新版本中被删除。后续可能会使用机械动力蓝图来取代它的存在。
