### ISSUE TITLE
StatLight调用Forge GetExistingBlockEntity存在线程死锁问题

### ISSUE THREAD

**Issue by mkZH0740** [Yorunina/No-Flesh-Within-Chest#59]
seed: 673153439430011875, 位置: x=-612.98, y=110.00, z=2098.64
抵达该位置后服务器即宕机，无法做出任何动作，log中提示[spark/]: Timed out waiting for world statistics，随后WatchDog检测到tick超时崩溃。

crash report:
https://gist.github.com/mkZH0740/83ca07297454e9b96f385bc6f0a1f3e6

**Comment by mkZH0740** [comment]
移除starlight模组后问题不再发生，参考[https://github.com/PaperMC/Starlight/issues/197](url)，建议在forge修复此问题前移除starlight模组

**Comment by Yorunina** [comment]
了解，后续跟进该问题。感谢反馈。
