### ISSUE TITLE
提一些意见，顺便说一个bug

### ISSUE THREAD

**Issue by 1561496327** [Yorunina/No-Flesh-Within-Chest#62]
开饰品开到鱼鳃，它直接自动装备，然后拿不下来重复死亡，只能删除mod重新进入游戏死亡后才能掉落。

至于我的意见看看就好，我觉得添加一个排异值会好一些，比如自己有一个排异值总值，多少百分比是安全，然后每到多少百分比就获得debuff，当然也可以低到某个程度获得正面buff，比如第一阶段画面扭曲、第二阶段减速、三阶虚弱，最终就是扣血什么的。
接着每个非自己或者没有去除排异的器官都添加增涨排异值的数值，比如每一段时间这些装在身体的器官会增加排异值总和。
至于降低排异值可以做药，添加一些草药什么的，野外生成什么村民交易然后让玩家批量种什么，这些做成降排异的药剂，分个高中低，降排异程度不同。再添加一个饰品位置，然后做一个排异值到多少就自动注射的饰品，可以把降排异的药剂放入饰品，就跟箭袋一样。至于永久去除器官排异的药应该将生成概率减少，或者制作难度增加，比如一个村庄应该生成一个或者没有，当然具体生成多少看实际情况。
开器官的ui建议美化，不是堆在一起，最好开敌人器官的时候可以时间暂停或者减慢老是拿器官被打死。

**Comment by Yorunina** [comment]
鱼鳃那个不是bug，是该饰品的特性，必须在水里才能摘下来。
下面的那些意见不是不想做，是无法实现，该内容应该提交在胸腔mod的Issue区而非整合包的。排异的内容完全是胸腔mod的逻辑，修改它需要对它的代码进行大刀阔斧的改动，在短期来看这样是绝对不可能的。
