### ISSUE TITLE
建议：希望获得女巫精酿效果的药水箭

### ISSUE THREAD

**Issue by someash** [Yorunina/No-Flesh-Within-Chest#65]
如题，希望能制作女巫精酿效果的药水箭
如果能让大师制箭师能有几率刷出女巫精酿效果的药水箭就更好了

**Comment by Yorunina** [comment]
goety中的精酿只有少部分是真正的药水效果，其余的并非是药水效果，而是一个药水被使用后触发的事件。
因此实现成本过高/无法实现。
