### ISSUE TITLE
显示bug（玻璃套装）

### ISSUE THREAD

**Issue by someash** [Yorunina/No-Flesh-Within-Chest#72]
![image](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/32922655/e760ec60-dd77-4971-ada3-3365938a4eab)
玻璃套装四件的中文全是乱码,
此外我穿上玻璃套装的时候，没有buff，（虽然不知道套装效果是啥）

**Comment by contionability** [comment]
你先看看你其它的套装是不是也乱码
如果不只是玻璃套的话就更换Java版本

**Comment by Yorunina** [comment]
已知问题，目前已统一换用Unicode解决衍生问题，0.2.1实装修复
