### ISSUE TITLE
铜套装合成冲突

### ISSUE THREAD

**Issue by yuukaguya** [Yorunina/No-Flesh-Within-Chest#73]
0.2.0版本中在工作台合成铜套，头盔、胸甲、鞋子均为冰火传说中的铜套装，而护腿为Extra Armor中的铜护腿

**Comment by contionability** [comment]
同，以及建议只保留冰火的铜套装

**Comment by Yorunina** [comment]
已知问题，修改其中一个铜套装为粗铜套装，0.2.1实装
