### ISSUE TITLE
建议：增加Better Advancements模组

### ISSUE THREAD

**Issue by contionability** [Yorunina/No-Flesh-Within-Chest#74]
现在的原版进度界面已经装不下所有成就了
会有几个无法显示完全跑到第二页（但是第二页无法切换）
这是加装了模组之后的效果
![窗口化全屏](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/78670017/7c4474a3-06f2-49f5-b93f-21ca5fa479da)
![缩小界面时](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/78670017/a000a585-135d-4fb1-8d74-a932d459ece5)
~~目前存在一个bug，在窗口化且窗口尺寸较小时，第二页的成就显示可能会错位且无法拖动，导致还是无法显示完全~~
已知bug：如果在游戏中途改变窗口大小，有可能会导致成就错位

**Comment by Yorunina** [comment]
采纳，0.2.1增添。

**Comment by RrkwM** [comment]
其实tab+enter可以给成就换页
