### ISSUE TITLE
[BUG] JEI的配方填充无法应用在背包内的工作台

### ISSUE THREAD

**Issue by popjdh** [Yorunina/No-Flesh-Within-Chest#76]
点击JEI的配方填充按钮后, 立刻出现报错如下:
```log
[15:45:27] [Netty Epoll Server IO #2/ERROR] [ne.mi.ne.si.IndexedMessageCodec/SIMPLENET]: Received invalid discriminator byte 14 on channel sophisticatedcore:channel
```
服务端未额外添加mod. 测试原版工作台可正常工作.

**Comment by popjdh** [comment]
经测试:
1. 单机模式下: 原版工作台, 背包工作台, TOM存储工作台均可填充
2. 联机模式下: 原版工作台, TOM存储工作台均可填充, 背包工作台填充出现上述报错
将服务端重新解压并运行可复现问题.

本人服务端与客户端均为Linux平台(Linux 6.7.6-arch1-1), 使用默认UTF-8文件编码. 在0.1.2的版本下无此问题.

**Comment by Yorunina** [comment]
可能是因为服务端中不包含EMI导致，今晚0.2.1版本时会查看具体原因。

**Comment by popjdh** [comment]
经测试0.2.1已修复此问题
