### ISSUE TITLE
[Bug] Lightmans Currency 模组可能造成严重的性能问题

### ISSUE THREAD

**Issue by 23650** [Yorunina/No-Flesh-Within-Chest#78]
问题描述：服务器 3人同屏的情况下，服务端 CPU 占用率居高不下，始终保持 95-100%

测试环境：WindowsServer-2012，硬件为 13900KF-2C8G，脆骨症 V0.2.0

服务器理论性能：半个月前游玩脆骨症 V0.1.2 时，以相同硬件配置，服务器 7-8 人同屏的情况下才能达到近 90% 的CPU占用，显然 V0.2.0 出现了严重的性能问题

Bug 复现：没尝试过，但已经找到了相同的 issue，那应该就不是偶发 Bug 吧...

- 从多份 Spark 性能分析报告来看，CPU 高占用的主要贡献为 Lightmans Currency 模组，详见 https://spark.lucko.me/Re5BOG1Ppz
- 经过一系列排查，最终确认与 Lightmans Currency 模组中的两个附魔有关（金钱修补 & 硬币磁力）
- 而在 Lightmans Currency 模组的 GitHub 页面中，我找到了同样关于性能的 issue 描述：[https://github.com/Lightman314/LightmansCurrency/issues/202；](https://github.com/Lightman314/LightmansCurrency/issues/202)
> 大概意思是说，在一些特定的 mod 组合下，使得刷出的其他生物装备上了 Lightmans Currency 的钱包，而钱包的两个附魔效果同样在生物身上也能触发，导致每个装备了钱包的生物都在频繁触发这两个附魔的效果，最终导致 CPU 不堪重负

- 该作者表示将在后续的版本中通过限制附魔的生效对象，来修复此问题
- 但我更好奇为什么怪物的身上会生成钱包（一脸疑惑

期望的效果：希望制作组能移除 Lightmans Currency 模组的附魔事件在怪物身上也能触发的奇怪 Bug（老实说，我不知道能否等到作者修复的那一天，所以才跑来开了个 issue OvO

**Comment by Yorunina** [comment]
该报告可置信该问题属实。经过翻阅源码、spark报告和原作者对于该情况的解释，目前认为是在EntityTick中，不断新建线程对实体进行饰品栏/物品附魔检测导致的性能问题。在进而导致在每个EntityTick引发了将近约20ms的延时。（实际上，任何生物都会引发这个线程的新建和缓存过程，仅仅是只有有钱包的生物会走到后面逻辑而已）
个人认为，导致这个问题能够被发现的部分原因在于大量饰品栏增加了每个EntityTick的运行负担，进而导致其能够被明显感受到。
下版本会尝试换用其他货币Mod，以规避该问题。（我并不认为禁用了附魔该问题就可以得到解决，除非自行修改后重新编译LC，但这只在万不得已的时候才会这么做）

**Comment by wendavid552** [comment]
Lightmans Currency似乎修复了这个问题，是否应该跟进更新？

**Comment by Yorunina** [comment]
LC作者已于新版本修复该问题
