### ISSUE TITLE
魔法巫师药水蜡烛粒子效果引发崩溃

### ISSUE THREAD

**Issue by 3264898377** [Yorunina/No-Flesh-Within-Chest#81]
![QQ图片20240303235722](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/162039548/448ba1fc-e2b2-46ff-ba39-e273350c5ff1)

**Comment by BlackRiceXY** [comment]
所以你为啥不发日志

**Comment by 3264898377** [comment]
[minecraft-exported-logs-2024-03-04T13-52-32.log](https://github.com/Yorunina/No-Flesh-Within-Chest/files/14477059/minecraft-exported-logs-2024-03-04T13-52-32.log)

**Comment by 3264898377** [comment]
这次是在单人档复现了一遍的日志，之前忘记保存了（）

**Comment by Yorunina** [comment]
魔法巫师药水蜡烛的粒子效果引发的崩溃，可以去对应的git下面提issue。不过考虑到本整合包用的魔法巫师就是自行编译的修复bug的版本，且魔法巫师mod更新实在过于怠惰. . .
后续版本可能会解决此问题。

**Comment by Yorunina** [comment]
目前暂时注释了魔法巫师药水粒子效果。该问题暂时得到解决，后续会跟进魔法巫师的版本更新。
