### ISSUE TITLE
Alex生物嬗变台复制物品

### ISSUE THREAD

**Issue by LunaGlaze** [Yorunina/No-Flesh-Within-Chest#85]
![(U~C_XN WKG9Z MZ0L2U8@K](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/120086484/010d1903-301b-4719-8155-9b2a8b17c5b3)
本人扩充包群内反馈Alex生物的“嬗变台”可以通过手动投入特殊物品从而消耗经验大量刷对应物品；只要是可以堆叠都可以直接用16雪球/末影珍珠直接换一组（64）
经测试例如深暗星尘碎片等难以获取的物品都可以如此刷取，可能对游戏有较大的影响，故此反馈。
另有mcmod刷取物品教程如下：
https://www.mcmod.cn/post/3229.html

**Comment by Yorunina** [comment]
新版本嬗变台已死
