### ISSUE TITLE
MMOparties mod会导致玩家在被机械手左键模式攻击的时候报错

### ISSUE THREAD

**Issue by Tioplate** [Yorunina/No-Flesh-Within-Chest#87]
[crash-2024-03-07_17.14.47-server.txt](https://github.com/Yorunina/No-Flesh-Within-Chest/files/14521240/crash-2024-03-07_17.14.47-server.txt)
错误报告如上，似乎是无法获取伤害来源的玩家导致

**Comment by Yorunina** [comment]
是这样。但这个问题整合包作者很难解决的了（原因是除非万不得已，否则我不想去改动别人的mod），而且触发的场景较为有限，可以暂时忽略。

除此之外，mmoparties在其他的一些场景也有一些异常（比如说无法接收到邀请、pvp禁用无效等），因此它也是在考虑被删除的一个mod。

**Comment by Tioplate** [comment]
单人自闭玩家还是删了这mod比较好

**Comment by contionability** [comment]
因为机械手是模拟的玩家实体，MMOparties并没有对此进行兼容，返回了Null
