### ISSUE TITLE
大胃王据说计算与描述不一致

### ISSUE THREAD

**Issue by MarkIc5785** [Yorunina/No-Flesh-Within-Chest#90]
![图片](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/26373753/edeef43f-334f-497d-8478-9923f4e44f09)
虽然Java编程不是很懂，但从逻辑上来说，我猜这里应该是value.id?

**Comment by Yorunina** [comment]
已知问题，开发分支已修复。
