### ISSUE TITLE
java无法创建虚拟机如图

### ISSUE THREAD

**Issue by Kay2333** [Yorunina/No-Flesh-Within-Chest#91]
<img width="298" alt="crash" src="https://github.com/Yorunina/No-Flesh-Within-Chest/assets/51441309/64a0a033-282c-4537-89e5-3005c3624ce1">

**Comment by Yorunina** [comment]
没有更多信息，这跟去医院只跟大夫说自己有病但不说病是什么是一个道理。
提出issue时请遵守issue规范，本issue将会关闭。

**Comment by Kay2333** [comment]
[Uploading 错误报告-2024-3-12_8.36.27.zip…]()
