### ISSUE TITLE
星尘碎片强化消失bug

### ISSUE THREAD

**Issue by 462557950** [Yorunina/No-Flesh-Within-Chest#97]
法术书的槽位强化会在退出游戏后消失，同时法书也无法再次强化。多人服务器和单人世界都存在这个bug
![QQ截图20240317064032](https://github.com/Yorunina/No-Flesh-Within-Chest/assets/163690969/78748cd9-a9ae-4113-86d6-ac72d43beae0)

**Comment by Yorunina** [comment]
应该是因为新版本的铁魔法会在游戏初始化的时候（或者其他节点）重置书本身的状态导致的。

**Comment by Yorunina** [comment]
碎片死了，最简单的解决方式了。等后面看看铁魔法稳定特性之后，怎么去解决这个问题。
