### ISSUE TITLE
关于使用起源增加多样性的可能

### ISSUE THREAD

**Issue by SXSWJSZY** [Yorunina/No-Flesh-Within-Chest#99]
“起源”和“起源：职业”我觉得都是可以加入的，选择职业后器官会有些许不同，例如选择战士职业，那肌肉力量和肋骨防御会略微增加（0.125是个不错的数字），但是速度会减慢，如果选择铁匠，那心脏就会自带一个特效，比如制作盔甲有概率获得额外护甲值之类，原模组这些职业的选择都是不能更改的，但是在脆骨症里就可以变成出生器官自带的特效（就是不知道技术上能不能实现），总之我觉得这对于增加游戏多样性是个好方法

**Comment by Yorunina** [comment]
当前整合包不会考虑，不过后续其他整合包可以采用这个设定。
